services:
  rasopus-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - RASOPUS_ADDRESS=0.0.0.0
      - RASOPUS_PORT=8000
      - ROCKET_SECRET_KEY=pnUM94/8LhhtSE1REEihKj7npG6+lvigAy4C885fIzY=
