services:
  rasopus-database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=rasopus
      - POSTGRES_PASSWORD=rasopus
      - POSTGRES_DB=rasopus
    ports:
      - "5432:5432"
    volumes:
      - /tmp/rasopus_postgres_data:/var/lib/postgresql/data

  rasopus-backend:
    depends_on:
      - rasopus-database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - RASOPUS_ADDRESS=0.0.0.0
      - RASOPUS_PORT=8000
      - RASOPUS_SECRET_KEY=pnUM94/8LhhtSE1REEihKj7npG6+lvigAy4C885fIzY=
      - RASOPUS_POSTGRES_USER=rasopus
      - RASOPUS_POSTGRES_PASSWORD=rasopus
      - RASOPUS_POSTGRES_HOST=rasopus-database
      - RASOPUS_POSTGRES_PORT=5432
      - RASOPUS_POSTGRES_DATABASE=rasopus
      - RASOPUS_POSTGRES_POOL_SIZE=10
      - RASOPUS_ARGON2_ITERATIONS=3
      - RASOPUS_ARGON2_MEMORY_MIB=70
