services:
  rasopus-database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=rasopus
      - POSTGRES_PASSWORD=rasopus
      - POSTGRES_DB=rasopus
    ports:
      - "5432:5432"
    volumes:
      - /tmp/rasopus_postgres_data:/var/lib/postgresql/data
  rasopus-backend:
    depends_on:
      - rasopus-database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - RASOPUS_ADDRESS=0.0.0.0
      - RASOPUS_PORT=8000
      - ROCKET_SECRET_KEY=pnUM94/8LhhtSE1REEihKj7npG6+lvigAy4C885fIzY=
      - RASOPUS_DATABASE_USER=rasopus
      - RASOPUS_DATABASE_PASSWORD=rasopus
      - RASOPUS_DATABASE_HOST=rasopus-database
      - RASOPUS_DATABASE_PORT=5432
      - RASOPUS_DATABASE_DATABASE=rasopus
      - RASOPUS_DATABASE_POOL_SIZE=10
